curl --request POST \
  --header 'content-type: application/json' \
  --url 'https://another-next-test.vercel.app/api/graphql' \
  --data '{"query":"query GetUser { getUser { id } }"}'

###
curl --request POST \
  --header 'content-type: application/json' \
  --url 'http://localhost:3000/api/graphql' \
  --data '{"query":"query GetUser { getUser { id } }"}'

###
curl --request POST \
  --header 'content-type: application/json' \
  --url 'http://localhost:3000/api/graphql' \
  --data '{"query":"mutation Mutation($slug: ID!) {revalidate(slug: $slug)}","variables":{"slug":"primer-post"},"operationName":"Mutation"}'

###

